### PR TITLE
Add Parsoid alignment styles to default stylesheet

### PR DESCRIPTION
**Pull request by samwilson**
Bug: T330949

### CODE REVIEW

**Comment by Tpt** [comment]
Thank you! Genuine question: is there a way to fetch it automatically from MediaWiki to avoid having to synchronize them again in the future? If yes, is it a good idea?

**Comment by samwilson** [comment]
I initially thought that would be the way to do this, yes, but actually I suspect that ereaders are less forgiving of complex CSS than web browsers are, so perhaps it's better that we do it manually. I'm not really sure though! :)

**Comment by Tpt** [comment]
> but actually I suspect that ereaders are less forgiving of complex CSS than web browsers are, so perhaps it's better that we do it manually. I'm not really sure though! :)

Yes, it makes a lot of sense. Thank you!

**Comment by samwilson** [comment]
@Tpt the failures here are fixed in #451.

**Review by Tpt — APPROVED** [review]
@samwilson Thank you!

**Pull request merged**
