### PR TITLE
Fix layout of 'back to Wikisource' button

### PR DESCRIPTION
**Pull request by samwilson**
Also add missing message.

Bug: https://phabricator.wikimedia.org/T277820

### CODE REVIEW

**Review by MusikAnimal — COMMENTED** [review]
As I understood it, we wanted to replace the space before the text with padding, such that there isn't an underline when hovering over it. I think what we have here is hugging the arrow icon too much, but my understanding of what Nicolas said could be wrong!

The alignment meanwhile looks perfect in Chrome but seems even more off now in Firefox, at on my end:
Screenshot from 2021-03-24 22-10-57

**Comment by samwilson** [comment]
> As I understood it, we wanted to replace the space before the text with padding, such that there isn't an underline when hovering over it. I think what we have here is hugging the arrow icon too much, but my understanding of what Nicolas said could be wrong!
> 
> The alignment meanwhile looks perfect in Chrome but seems even more off now in Firefox, at on my end:
> Screenshot from 2021-03-24 22-10-57

Oh, I totally thought it was about *reducing* the gap between them. But it makes sense, what you say! I'll update it to increase the space, and move the text down a bit also (although I'm always worried about pixel-perfect moving of text; it never seems to work everywhere!).

I did wonder about the hover underline. @nayoub does that stay or go?

**Comment by nayoub** [comment]
Awesome! Yes absolutely @samwilson 
The hover underline stays, the only issue on this was that we had an empty space underlined on hover before the 'B' on "Back to Wikisource".

**Comment by samwilson** [comment]
Okay cool, thanks. I've moved the underline to just be on the text bit.

**Pull request merged**
